# Generated by Django 6.0.4 on 2026-04-19 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('UTILISE', 'Utilisé'), ('DEFAILLANT', 'Défaillant')], default='DISPONIBLE', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uids', to='catalogue.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uids', to='catalogue.produit')),
            ],
        ),
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ENTREE_FOURNISSEUR', '📦 Entrée Fournisseur'), ('SORTIE_UTILISATION', '🔧 Sortie Utilisation'), ('SORTIE_VENTE', '💰 Sortie Vente'), ('RETOUR_FOURNISSEUR', '↩️  Retour Fournisseur'), ('RETOUR_CLIENT', '↩️  Retour Client'), ('TRANSFERT_ENTREE', '➡️  Transfert Entrée'), ('TRANSFERT_SORTIE', '⬅️  Transfert Sortie'), ('AJUSTEMENT_PLUS', '📋 Ajustement +'), ('AJUSTEMENT_MOINS', '📋 Ajustement -'), ('INITIALISATION', '🚀 Initialisation')], max_length=25)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('numero_bon', models.CharField(blank=True, max_length=50)),
                ('fournisseur', models.CharField(blank=True, max_length=100)),
                ('motif', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField()),
                ('entrepot_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_entree', to='catalogue.entrepot')),
                ('entrepot_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_sortie', to='catalogue.entrepot')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_stock', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'Événement de stock',
                'ordering': ['-created_at'],
                'unique_together': {('produit', 'version')},
            },
        ),
    ]
