# Generated by Django 6.0.4 on 2026-04-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_stockuid'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('derniere_version', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalogue.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalogue.produit')),
            ],
            options={
                'unique_together': {('produit', 'entrepot')},
            },
        ),
        migrations.DeleteModel(
            name='StockUID',
        ),
    ]
