# Generated by Django 6.0.4 on 2026-04-19 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_theorique', models.IntegerField()),
                ('stock_compte', models.IntegerField(blank=True, null=True)),
                ('ecart', models.IntegerField(default=0)),
                ('valide', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventaires.inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.produit')),
            ],
        ),
    ]
