# Generated by Django 6.0.4 on 2026-04-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_stockuid'),
        ('inventaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires', to='catalogue.entrepot'),
        ),
    ]
