# Generated by Django 6.0.4 on 2026-04-20 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_stockuid'),
        ('inventaires', '0002_inventaire_entrepot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_inventaire', to='catalogue.entrepot'),
        ),
    ]
