# Generated by Django 6.0.4 on 2026-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0003_ligneinventaire_entrepot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneinventaire',
            name='stock_theorique',
            field=models.IntegerField(default=0),
        ),
    ]
