# Generated by Django 6.0.4 on 2026-04-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('type_code', models.CharField(choices=[('BARCODE', 'Code-barres 1D'), ('QR', 'QR Code'), ('EAN', 'EAN / GS1'), ('MANUEL', 'Saisie manuelle')], default='QR', max_length=10)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('UTILISE', 'Utilisé'), ('DEFAILLANT', 'Défaillant')], default='DISPONIBLE', max_length=15)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uids', to='catalogue.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uids', to='catalogue.produit')),
            ],
        ),
    ]
